/**
 * Full X profile setup — do this BEFORE first post or ads.
 * Manual paste into x.com/settings (no auto-post API).
 */
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { DATA_DIR, assertDataDir, env } from "../config.js";
import { getProject } from "../projects/registry.js";
import { brandVoice } from "../brands.js";
import { newId } from "../store.js";

export interface XProfilePack {
  id: string;
  projectId: string;
  at: number;
  outputPath: string;
  markdown: string;
}

function handleFor(projectId: string): string {
  if (projectId === "magmos") {
    return (env("MAGOS_X_HANDLE") || env("VEIL_X_HANDLE") || "henrysammarfo").replace(/^@/, "");
  }
  return (env("VEIL_X_HANDLE") || "henrysammarfo").replace(/^@/, "");
}

function magmosProfile(): string {
  const demo = env("MAGOS_DEMO_URL") || "https://magmoslabs.vercel.app";
  const repo = env("MAGOS_REPO_URL") || "https://github.com/henrysammarfo/magmoslabs";
  const handle = handleFor("magmos");

  return `# X PROFILE SETUP — Magmos Labs
_Do this fully before first post, blue tick, or ads._

**Account:** [@${handle}](https://x.com/${handle})
**Live demo:** ${demo}
**Repo:** ${repo}

---

## 1. Display name (max ~50 chars)

\`\`\`
Magmos Labs
\`\`\`

Alt if personal brand first:
\`\`\`
Henry · Magmos
\`\`\`

## 2. Handle

Keep **@${handle}** for now (blue tick + ads attach here).
Optional later: @MagmosLabs if available — then update MAGOS_X_HANDLE.

## 3. Bio (≤160 chars — paste exactly)

Primary (recommended):
\`\`\`
Composable yield-dollar on Sui. AURUM · sAURUM · forge → smelt → refine. Testnet live — real Move txs, not a mockup.
\`\`\`

Short alt:
\`\`\`
Forge a yield-dollar on Sui. AURUM / sAURUM. Thermal limits. Testnet live.
\`\`\`

## 4. Location

\`\`\`
Accra · Sui
\`\`\`

## 5. Website / link in bio

Paste **demo first** (not GitHub):
\`\`\`
${demo}
\`\`\`

GitHub goes in pinned reply / About, not bio link.

## 6. Profile photo

**Ready file (upload this):**
\`veil-xbot/assets/brand/magmos-x-avatar.png\`

- Square crop, high contrast
- Prefer: Magmos mark / forge glyph on dark field
- Avoid: generic AI face, neon city, gold coins
- Size: 400×400 min (upload 800×800)

Prompt used:
\`\`\`
Minimal brand mark for Magmos Labs — abstract forge / molten metal glyph, deep charcoal background, single ember accent, no text, no coins, square logo, flat vector
\`\`\`

## 7. Header / banner (1500×500)

**Ready file (upload this):**
\`veil-xbot/assets/brand/magmos-x-banner.png\`

Prompt used:
\`\`\`
Wide X banner, dark industrial forge atmosphere, subtle molten line across center, Magmos Labs wordmark left, no people, no crypto clichés, cinematic grade, 3:1
\`\`\`

## 8. Professional / Premium

- [ ] Subscribe **X Premium** on @${handle} → https://x.com/i/premium_sign_up
- [ ] Complete ID verification if prompted (blue tick)
- [ ] Turn on **longer video** + edit post if available
- [ ] Do NOT buy Premium+ until ads are running

## 9. Pinned post (after first video — not before)

Caption (main post — NO link):
\`\`\`
Forge tx landed. Not a mockup.
\`\`\`

First reply (within 60s):
\`\`\`
Try it on testnet → ${demo}
Contracts + docs → ${repo}
\`\`\`

## 10. Communities (join today)

| Community | First action |
|-----------|----------------|
| Build in Public | Reply with forge screenshot (no link) |
| DeFi | Watch + reply under 1 yield thread |
| Sui | Lurk day 1 — post after first video has traction |
| Startup | Optional founder grind reply |

Full list: COMMUNITIES.md

## 11. Settings hygiene

- [ ] Sensitive media: off
- [ ] Protect posts: **off** (public)
- [ ] Allow message requests from verified: on (after Premium)
- [ ] Mute: spam bots, APY shillers
- [ ] Highlights: empty until first 3 posts

## 12. Day-0 checklist (order matters)

1. [ ] Photo + banner uploaded
2. [ ] Display name + bio + location + website saved
3. [ ] X Premium subscribed (blue tick in progress)
4. [ ] Join 3 communities
5. [ ] Record 45–60s forge screen on ${demo}
6. [ ] \`npm run magmos-ad recording.webm\`
7. [ ] Post video → reply with link → pin
8. [ ] \`npm run engage-batch\` same day
9. [ ] Promote winning creative (X Ads) after organic has 1h+

## 13. What NOT to put on profile

- APY / "stable yield" promises
- Veil trading story (separate product — post Magmos first)
- Empty "building something" with no proof link
- Hashtag soup in bio

---

Generated by veil-xbot · \`npm run x-profile magmos\`
`;
}

function veilProfile(): string {
  const demo = env("VEIL_DEMO_URL") || "https://veil-reviewer.vercel.app";
  const waitlist = env("VEIL_WAITLIST_URL") || "";
  const handle = handleFor("veil");
  return `# X PROFILE SETUP — Veil
**Account:** @${handle}
**Demo:** ${demo}
${waitlist ? `**Waitlist:** ${waitlist}` : ""}

Bio:
\`\`\`
Stealth execution on Sui. Intent off-chain → DeepBook Predict fills. Real testnet — real losses.
\`\`\`

Website: ${waitlist || demo}
`;
}

export function buildXProfilePack(projectId: string): XProfilePack {
  const project = getProject(projectId);
  const voice = brandVoice(projectId);
  void voice;
  void project;

  const markdown =
    projectId === "magmos" ? magmosProfile() : projectId === "veil" ? veilProfile() : magmosProfile();

  assertDataDir();
  const dir = join(DATA_DIR, "growth");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const id = newId("xprofile");
  const outputPath = join(dir, `X-PROFILE-${projectId.toUpperCase()}.md`);
  writeFileSync(outputPath, markdown);
  writeFileSync(join(dir, "X-PROFILE.md"), markdown);
  writeFileSync(join(dir, `${id}.json`), JSON.stringify({ id, projectId, at: Date.now() }, null, 2));

  return { id, projectId, at: Date.now(), outputPath, markdown };
}
